name: "🎉 Release"
run-name: "Create release ${{ github.event.inputs.tag }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The release tag"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Release"
      uses: ./
      with:
        tag: ${{ github.event.inputs.tag }}
